// src/angular/components/add-item.component.ts
import {
  Component,
  EventEmitter,
  Input,
  Output,
} from '@angular/core';

@Component({
  selector: 'app-add-item',
  template: `
    <div class="input-group add-item col-6 p-0">
      <input
        #newItemInput
        aria-describedby="addButton"
        class="form-control"
        type="text"
        [attr.aria-label]="placeholder"
        [placeholder]="placeholder"
      />
      <div class="input-group-append">
        <button
          class="btn btn-primary"
          id="addButton"
          type="button"
          (click)="handleClick(newItemInput)"
        >{{ buttonText }}</button>
      </div>
    </div>
  `,
})
export class AddItemComponent {
  @Input() buttonText: string;
  @Input() placeholder: string;
  @Output() addItem = new EventEmitter<string>();

  handleClick(input: HTMLInputElement) {
    this.addItem.emit(input.value);
    input.value = '';
  }
}

// src/react/components/add-item.jsx
class AddItem extends React.Component {
  constructor() {
    super();
    this.state = {
      value: '',
    };
    this.handleChange = this.handleChange.bind(this);
    this.handleClick = this.handleClick.bind(this);
  }

  handleClick() {
    this.props.onAdd(this.state.value);
    this.setState({ value: '' });
  }

  handleChange(event) {
    this.setState({ value: event.target.value });
  }

  render() {
    const {
      handleChange,
      handleClick,
      state: { value },
    } = this;

    return (
      <div className="input-group add-item col-6 p-0">
        <input
          aria-describedby="addButton"
          aria-label="Item name"
          className="form-control"
          onChange={handleChange}
          placeholder="Item name"
          type="text"
          value={value}
        />
        <div className="input-group-append">
          <button
            className="btn btn-primary"
            id="addButton"
            onClick={handleClick}
            type="button"
          >
            Add
          </button>
        </div>
      </div>
    );
  }
}
