// src/react/components/container.jsx
class Container extends React.Component {
  initialItems = [
    { label: 'Foo', done: false },
    { label: 'Bar', done: true },
  ];

  constructor() {
    super();
    this.state = {
      items: this.initialItems,
    };
    this.handleAdd = this.handleAdd.bind(this);
    this.handleChange = this.handleChange.bind(this);
  }

  handleAdd(label) {
    const exists = this.state.items.findIndex((item) => item.label === label) !== -1;
    if (!exists) {
      this.setState({
        items: [
          ...this.state.items,
          {
            label,
            done: false,
          },
        ],
      });
    }
  }

  handleChange(item, done) {
    const items = this.state.items.map((i) => {
      if (i === item) {
        i.done = done;
      }
      return i;
    });
    this.setState({ items });
  }

  render() {
    const {
      handleAdd,
      handleChange,
      state: { items },
    } = this;

    return (
      <main className="container-fluid">
        <h1>To-Do App</h1>
        <Info items={items} />
        <List
          items={items}
          onChange={handleChange}
        />
        <AddItem onAdd={handleAdd} />
      </main>
    );
  }
}

// src/angular/components/container.component.ts
import { Component } from '@angular/core';
import { Item } from '../interfaces/item';

@Component({
  selector: 'my-app',
  template: `
    <main class="container-fluid">
      <h1>{{ title }}</h1>
      <app-info [items]="items"></app-info>
      <app-list [items]="items"></app-list>
      <app-add-item
        buttonText="Add"
        placeholder="Item name"
        (addItem)="handleAddItem($event)"
      ></app-add-item>
    </main>
  `
})
export class ContainerComponent {
  items: Item[] = [
    { label: 'Foo', done: false },
    { label: 'Bar', done: true },
  ];
  title = 'Angular To-Do App';

  handleAddItem(label: string) {
    const exists = this.items.find((item) => item.label === label);
    if (!exists) {
      const newItem = {
        label,
        done: false,
      };
      this.items.push(newItem);
    }
  }
}
